django_Keijiban/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('keijiban.urls')),
    path('admin/', admin.site.urls),
]

keijiban/urls.py
from django.urls import path
from .views import Index, ThreadView, Create, CategoryView

urlpatterns = [
    path('', Index.as_view(), name="index"),
    path('threads/<pk>/', ThreadView.as_view(), name='thread'),
    path('create/', Create.as_view(), name='create'),
    path('category/<pk>/', CategoryView.as_view(), name='category'),
]

keijiban/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(
        max_length=255,
        blank=False,
        null=False,)

    def __str__(self):
        return self.name

class Thread(models.Model):
    title = models.CharField(
        max_length=255,
        blank=False,
        null=False,
        default="無題")

    view = models.IntegerField(
        blank=True,
        null=False,
        default=0)

    category = models.ForeignKey(
        Category,
        null=True,
        on_delete=models.SET_NULL)

    def __str__(self):
        return self.title


class Tag(models.Model):
    type = models.CharField(
        max_length=15,
        blank=False,
        null=False,
        unique=True)

    def __str__(self):
        return self.type


class Post(models.Model):
    IPaddress = models.GenericIPAddressField(
        blank=False,
        null=False)

    ipID = models.CharField(
        max_length=8,
        blank=True,
        null=False,
        default="xxxxxxxx")

    created = models.DateTimeField(
        auto_now_add=True,
        editable=False,
        blank=False,
        null=False)

    name = models.CharField(
        max_length=15,
        blank=False,
        null=False,
        default="名無しさん")

    body = models.TextField(
        max_length=255,
        blank=False,
        null=False)

    thread = models.ForeignKey(
        Thread,
        on_delete=models.CASCADE)

    tags = models.ManyToManyField(
        Tag,
        blank=True)

    def __str__(self):
        return str(self.id)

keijiban/forms.py
from django import forms
from .models import Thread, Post

widget_textarea = forms.Textarea(
    attrs={
        "class": "form-control",
        "rows" : 4,
        "placeholder" : "投稿したい内容を入力してね"
    }
)

widget_textinput = forms.TextInput(
    attrs={
        "class": "form-control",
        "value" : "名無しさん"
    }
)

class ThreadForm(forms.ModelForm):
    class Meta:
        model = Thread
        fields=(
           'category',
           'title',
           )
        labels ={
           'category':'カテゴリ',
           'title':'タイトル',
        }

class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields =(
           'name',
           'body',
           )
        labels= {
           'name':'名前',
           'body':'投稿内容',
        }


class SearchForm(forms.Form):
    name = forms.CharField(label="ニックネーム", widget=widget_textinput)

keijiban/views.py
from django.views.generic import ListView, DetailView, UpdateView, CreateView
from .models import Thread, Category, Tag, Post
from django.utils import timezone
from ipware import get_client_ip
from .functions import get
from .forms import ThreadForm, PostForm
from django.urls import reverse_lazy
from django.shortcuts import redirect


class Index(ListView):
    model = Thread
    paginated_by = 10


class CategoryView(DetailView):
    model = Category

    def get_query_set():
        return Category.objects.all().filter(pk = thread__category)


class ThreadView(UpdateView):
    template_name = 'keijiban/thread.html'
    model = Thread
    form_class = PostForm

    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        form = self.form_class(self.request.GET or None)
        context.update({'form':form})
        return context

    def form_valid(self, form):
        t = form.save()
        # IPアドレスの取得　参考：https://qiita.com/3244/items/0b47d3ad91968fe15eb9
        client_addr, is_routable = get_client_ip(self.request, request_header_order=['X_FORWARDED_FOR', 'REMOTE_ADDR'])
        Post.objects.create(
            IPaddress = client_addr,
            ipID = get.hashing(client_addr),
            created = timezone.now(),
            name = form.data.get('name'),
            body = form.data.get('body'),
            thread=t,
            )
        return redirect('/threads/' + str(self.object.pk))

    def get_absolute_url(self):
        return reverse_lazy("thread", args=[self.object.pk])


class Create(CreateView):
    model = Thread
    form_class = ThreadForm
    form_class2 = PostForm

    def get_context_data(self, **kwargs):
        context= CreateView.get_context_data(self, **kwargs)
        form = self.form_class(self.request.GET or None)
        form2 = self.form_class2(self.request.GET or None)
        context.update({'form':form})
        context.update({'form2':form2})
        return context

    def form_valid(self, form):
        t = form.save()
        # IPアドレスの取得　参考：https://qiita.com/3244/items/0b47d3ad91968fe15eb9
        client_addr, is_routable = get_client_ip(self.request, request_header_order=['X_FORWARDED_FOR', 'REMOTE_ADDR'])
        Post.objects.create(
            IPaddress = client_addr,
            ipID = get.hashing(client_addr),
            created = timezone.now(),
            name = form.data.get('name'),
            body = form.data.get('body'),
            thread=t,
            )
        return CreateView.form_valid(self, form)

    def get_absolute_url(self):
        return reverse_lazy("thread", args=[self.object.pk])

keijiban/templates/_base.html
{% load static %}
{% load Myfunc %}

<!DOCTYPE html>
<html lang="ja">

    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'scss/custom.scss' %}">
        {% block pageTitle %}
        <title>Django匿名掲示板</title>
        {% endblock %}
    </head>

    <body>
        <nav class="navbar sticky-top navbar-expand-lg navbar-dark" style="background-color: #4B4A59">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">Django匿名掲示板</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'index' %}">スレッド一覧</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                カテゴリー
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                {% for c in getCategory_list %}
                                <li><a class="dropdown-item" href="{% url 'category' c.pk %}">{{ c.name }}</a></li>
                                <li><hr class="dropdown-divider"></li>
                                {% empty %}
                                <li><a class="dropdown-item disabled" tabindex="-1" aria-disabled="true">カテゴリがありません</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'create' %}">スレッド作成</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="スレッド名など" aria-label="Search">
                        <button class="btn btn-outline-light" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
        {% block breadcrumb %}
        <nav style="--bs-breadcrumb-divider: '>'; background-color: #B7BCBF;" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page">Home</li>
            </ol>
        </nav>
        {% endblock %}

        {% block main %}
        コンテンツがありません。
        {% endblock %}

        <footer style="text-align: center;">
            <p>
                written by Akari Katsuma, November 2021.
            </p>
        </footer>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
        <script src="{% static 'bootstrap/js/src/button.js' %}"></script>
    </body>
</html>

keijiban/templates/keijiban/category_detail.html
{% extends "_base.html" %}
{% load humanize %}


{% block pageTitle %}
<title>{{ object.name }} - Django掲示板</title>
{% endblock %}

{% block breadcrumb %}
<nav style="--bs-breadcrumb-divider: '>'; background-color: #B7BCBF;" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index'%}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ object.name }}</li>
    </ol>
</nav>
{% endblock %}

{% block main %}
<h2>{{ object.name }}のスレッド一覧</h2>
{% if object.thread_set.all %}
    作成日時順<br>
    {% for t in object.thread_set.all %}
    <div class="card" style="width: 18rem;">
        <div class="card-body" style="background:#f2ede8;">
            <a href="{% url 'thread' t.id %}">
                <h5 class="card-title">{{ t.title }}</h5>
            </a>
            <h6 class="card-subtitle mb-2 text-muted">作成者 {{ t.post_set.first.name }}</h6>
            <p class="card-text">最終更新 {{ t.post_set.last.created | naturaltime }}</p>
        </div>
        <div class="card-footer" style="display: flex;justify-content: space-between; background:#f2ede8; color:#AA8279;">
            <span class="badge rounded-pill text-info  border border-info badge-outlined">{{t.category}}</span>{{t.view| intcomma }} view　{{t.post_set.all| length | add:"-1"}} replies
        </div>
    </div>
    <br>
    {% endfor %}
    <nav aria-label="...">
        <ul class="pagination">
            <li class="page-item disabled">
                <span class="page-link" href="#" tabindex="-1" aria-disabled="true">前へ</span>
            </li>
            <li class="page-item active" aria-current="page">
                <span class="page-link" style="background-color: #AA8279; border-color: #AA8279;" href="#">1</span>
            </li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
                <a class="page-link" href="#">次へ</a>
            </li>
        </ul>
    </nav>
{% else %}
    <p>まだ{{ object.name }}のスレッドはありません。新しいスレッドを作りませんか？</p>
    <a class="btn" style="background:#f2ede8; color:#4B4A59; border: 1px solid #AA8279;" href="{% url 'create' %}" role="button">スレッドを作成する</a><br>
{% endif %}

{% endblock %}

keijiban/templates/keijiban/post_list.html
{% extends "_base.html" %}
{% load l10n %}


{% block pageTitle %}
<title>{{ object_list.first.name }} - Django掲示板</title>
{% endblock %}

{% block breadcrumb %}
<nav style="--bs-breadcrumb-divider: '>'; background-color: #B7BCBF;" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Library</li>
    </ol>
</nav>
{% endblock %}

{% block main %}
<h2>ここにタイトル{{ object_list.first.name }}</h2>
<hr>
<div id='board'>
    <p id='default'>
        まだ書き込みはありません。
    </p>
    {% for p in object_list %}
    <p>
        {{ p.id }}、{{ p.name }}、{{ p.created|localize }}、{{ p.IPaddress }}
    </p>
    <p>
        {{ p.body }}
    </p>
    {% endfor %}
</div>
<input id="update" type="button" value="更新"/>

<form id='mes_form'>
    <table id='mes_table'>
        <tr>
            <th>名前</th>
            <td>
                <input id="namae" type="text" form="mes_form" value="名無しさん">
            </td>
        </tr>
        <tr>
            <th>メッセージ</th>
            <td>
                        <textarea id="message" rows="4" cols="40" form="mes_form"
                                  placeholder="投稿したいメッセージを入力してください。"></textarea>
            </td>
        </tr>
        <tr>
            <th>オプション</th>
            <td>
                <label><input name = "option" type="checkbox" value="big"  form="mes_form"/>文字を大きくする</label>
                <label><input name = "option" type="checkbox" value="bold"  form="mes_form"/>太字</label>
                <label><input name = "option" type="checkbox" value="ita"  form="mes_form"/>斜体</label>
            </td>
        </tr>
    </table>
    <label id="error" for="send" style="color: red;"></label><br>
    <input id="send" type="button" value="投稿"  form="mes_form"/>
</form>
{% endblock %}

keijiban/templates/keijiban/thread.html
{% extends "_base.html" %}


{% block pageTitle %}
<title>{{ object.title }} - Django掲示板</title>
{% endblock %}

{% block breadcrumb %}
<nav style="--bs-breadcrumb-divider: '>'; background-color: #B7BCBF;" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index'%}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'category' object.category.id %}">{{ object.category }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ object.title }}</li>
    </ol>
</nav>
{% endblock %}

{% block main %}
{% autoescape on %}
<h2>{{ object.title }}</h2>
<hr>
<div id='board'>
    {% for p in object.post_set.all %}
    <p>
        {{ forloop.counter }}：{{ p.name }} ID:{{ p.ipID }}
    </p>
    <p>
        {{ p.body }}
    </p>
    <p>
        {{ p.tag_set.all }}
    </p>
    <p style="text-align: right">
        {{ p.created | date:"Y/m/d H:i:s" }}
    </p>
    <hr>
    {% empty %}
    <p>書き込みがありません。</p>
    {% endfor %}
</div>

<input class="btn" style="background:transparent; color:#4B4A59; border: 1px solid #AA8279;" type="reset" value="更新">

<br><br><br>
<h3>スレッドに返信する</h3>
{% for error in form.non_field_errors %}
<div class="alert alert-danger" role="alert">
    {{ error }}
</div>
{% endfor %}
<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <p>
        <label>{{ field.label }}</label>
        {{ field }}
    </p>
    {% endfor %}
    <input class="btn text-light" style="background: #AA8279" type="submit" value="投稿">
</form>
{% endautoescape %}
{% endblock %}

keijiban/templates/keijiban/thread_detail.html
{% extends "_base.html" %}


{% block pageTitle %}
<title>{{ object.title }} - Django掲示板</title>
{% endblock %}

{% block breadcrumb %}
<nav style="--bs-breadcrumb-divider: '>'; background-color: #B7BCBF;" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index'%}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'category' object.category.id %}">{{ object.category }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ object.title }}</li>
    </ol>
</nav>
{% endblock %}

{% block main %}
{% autoescape on %}
<h2>{{ object.title }}</h2>
<hr>
<div id='board'>
    {% for p in object.post_set.all %}
    <p>
        {{ forloop.counter }}：{{ p.name }} ID:{{ p.ipID }}
    </p>
    <p>
        {{ p.body }}
    </p>
    <p>
        {{ p.tag_set.all }}
    </p>
    <p style="text-align: right">
        {{ p.created | date:"Y/m/d H:i:s" }}
    </p>
    <hr>
    {% empty %}
    <p>書き込みがありません。</p>
    {% endfor %}
</div>

<input class="btn" style="background:transparent; color:#4B4A59; border: 1px solid #AA8279;" type="reset" value="更新">

<br><br><br>
<h3>スレッドに返信する</h3>
{% for error in form.non_field_errors %}
<div class="alert alert-danger" role="alert">
    {{ error }}
</div>
{% endfor %}
<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <p>
        <label>{{ field.label }}</label>
        {{ field }}
    </p>
    {% endfor %}
    <input class="btn text-light" style="background: #AA8279" type="submit" value="投稿">
</form>
{% endautoescape %}
{% endblock %}

keijiban/templates/keijiban/thread_form.html
{% extends "_base.html" %}


{% block pageTitle %}
<title>新規スレッド作成 - Django掲示板</title>
{% endblock %}

{% block breadcrumb %}
<nav style="--bs-breadcrumb-divider: '>'; background-color: #B7BCBF;" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index'%}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">新規スレッド作成</li>
    </ol>
</nav>
{% endblock %}

{% block main %}
<h2>新規スレッド作成</h2>
<form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        {{ form2.as_table }}
        <tr><td></td><td><input type="submit" value="投稿" class="btn text-light" style="background:#4B4A59;"/>
            <a class="btn" type="submit" href="{% url 'index' %}" role="button"/>やめる</a></td></tr>
    </table>
</form>
{% endblock %}

keijiban/templates/keijiban/thread_list.html
{% extends "_base.html" %}
{% load humanize %}
{% load static %}


{% block pageTitle %}
<link rel="stylesheet" type="text/css" href="{% static 'scss/indexTable.css' %}">
<title>Django掲示板トップ</title>
{% endblock %}

{% block main %}
<p>
    当掲示板へようこそ！<br>
    特定の個人や団体を誹謗・中傷するような内容の書き込みは避け、マナーを守って使いましょう。
</p>
<div>
    {% now "Y年m月d日H時i分" %}現在、{{ object_list | length | intcomma }}個のスレッドがあります。<br>
    <a class="btn" style="background:#f2ede8; color:#4B4A59; border: 1px solid #AA8279;" href="{% url 'create' %}" role="button">スレッドを作成する</a><br>
</div>
<hr>
<h3>スレッド一覧</h3>
{% if object_list %}
    作成日時順<br>
    {% for t in object_list %}
    <div class="card" style="width: 18rem;">
        <div class="card-body" style="background:#f2ede8;">
            <a href="{% url 'thread' t.id %}">
                <h5 class="card-title">{{ t.title }}</h5>
            </a>
            <h6 class="card-subtitle mb-2 text-muted">作成者 {{ t.post_set.first.name }}</h6>
            <p class="card-text">最終更新 {{ t.post_set.last.created | naturaltime }}</p>
        </div>
        <div class="card-footer" style="display: flex;justify-content: space-between; background:#f2ede8; color:#AA8279;">
            <span class="badge rounded-pill text-info  border border-info badge-outlined">{{t.category}}</span>{{t.view| intcomma }} view　{{t.post_set.all| length | add:"-1"}} replies
        </div>
    </div>
    <br>
    {% endfor %}
    <nav aria-label="...">
        <ul class="pagination">
            <li class="page-item disabled">
                <span class="page-link" href="#" tabindex="-1" aria-disabled="true">前へ</span>
            </li>
            <li class="page-item active" aria-current="page">
                <span class="page-link" style="background-color: #AA8279; border-color: #AA8279;" href="#">1</span>
            </li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
                <a class="page-link" href="#">次へ</a>
            </li>
        </ul>
    </nav>
{% else %}
    <p>まだスレッドはありません。新しいスレッドを作りませんか？</p>
{% endif %}
{% endblock %}